### ISSUE TITLE
Preview of About Grep Plugin documentation.

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-plugin-grep#1]
I wrote this plugin to finish up the html conversion on my numerous sites. On my laptop it can fetch 50 or more pages a second. Over the LAN my aging mini I still delivers 10 or 20 pages a second. Elsewhere much slower I presume. The markup it interprets could be sent to the server though a server-side plugin with this client-centric version for fallback. The internal interpreter is meant to expand as new needs surface. I'd be pleased to see it distributed with our other plugins.

![image](https://cloud.githubusercontent.com/assets/12127/5609663/a46daa96-945a-11e4-8c4b-2a0884177351.png)

![image](https://cloud.githubusercontent.com/assets/12127/5609651/7ab31524-945a-11e4-93a4-8bc431c5ef1e.png)

**Comment by paul90** [comment]
I have updated a couple of the devDependencies and selected the `other` category in `factory.json`

Initial version published as **wiki-plugin-grep@0.1.0**
